textos = {
    "bienvenida": "Benvenuto al Sistema",
    "inicio_sesion_paciente": "Accedi come Paziente",
    "inicio_sesion_administrados": "Accedi come Amministratore",
    "salir": "Esci",
    "iniciar_sesion_como": "Accedi come",
    "nombre": "Nome:",
    "correo_electronico": "Email:",
    "contrasena": "Password:",
    "enviar": "Invia",
    "regresar": "Indietro",
    "bienvenido": "Benvenuto,",
    "citas_registradas": "Appuntamenti registrati",
    "horarios": "Orari",
    "registro_medico": "Registro medico",
    "estadisticas": "Statistiche",
    "historial_citas": "Storico utenti",
    "cerrar_sesion": "Disconnetti",
    "edad": "Età:",
    "sexo": "Sesso (m per maschio o f per femmina):",
    "peso": "Peso [kg]:",
    "motivo": "Motivo dell'appuntamento:",
    "error": "Errore",
    "error_edad": "L'età deve essere un numero positivo.",
    "error_peso": "Il peso deve essere un numero positivo.",
    "error_sexo": "Il sesso deve essere M o F.",
    "error_motivo": "Il motivo dell'appuntamento non può essere vuoto.",
    "guarda_continuar": "Salva e continua",
    "lista_medicos": "Elenco dei medici",
    "busqueda_medicos": "Ricerca medici",
    "ordenar_nombre": "Ordina per nome",
    "ordenar_especialidad": "Ordina per specializzazione",
    "ordenar_precio": "Ordina per prezzo",
    "foto": "Foto",
    "especialidad": "Specializzazione",
    "precio": "Prezzo (MXN)",
    "accion": "Azione",
    "seleccionar": "Seleziona",
    "cirugia_general": "Chirurgia generale",
    "neurocirugia": "Neurochirurgia",
    "diagnostico": "Diagnostica",
    "cirugia_cardiotoracica": "Chirurgia cardiotoracica",
    "obstetricia": "Ostetricia / Neonatologia",
    "plastica": "Chirurgia plastica / Otorinolaringoiatria",
    "pediatrica": "Chirurgia pediatrica",
    "oncologia": "Oncologia",
    "cambiar_idioma": "Cambia lingua",
    "espaniol": "Spagnolo",
    "ingles": "Inglese",
    "frances": "Francese",
    "italiano": "Italiano",
    "aleman": "Tedesco",
    "chino": "Cinese",
    "japones": "Giapponese",
    "portugues": "Portoghese",
    "titulo_ventana": "Sistema di accesso",
    "calendario": "Calendario",
    "lunes": "Lunedì",
    "martes": "Martedì",
    "miercoles": "Mercoledì",
    "jueves": "Giovedì",
    "viernes": "Venerdì",
    "sabado": "Sabato",
    "domingo": "Domenica",
    "horario": "Orario"
}
