textos = {
    "bienvenida": "システムへようこそ",
    "inicio_sesion_paciente": "患者としてログイン",
    "inicio_sesion_administrados": "管理者としてログイン",
    "salir": "終了",
    "iniciar_sesion_como": "としてログイン",
    "nombre": "名前：",
    "correo_electronico": "メールアドレス：",
    "contrasena": "パスワード：",
    "enviar": "送信",
    "regresar": "戻る",
    "bienvenido": "ようこそ、",
    "citas_registradas": "登録された予約",
    "horarios": "スケジュール",
    "registro_medico": "医療記録",
    "estadisticas": "統計",
    "historial_citas": "ユーザー履歴",
    "cerrar_sesion": "ログアウト",
    "edad": "年齢：",
    "sexo": "性別（m：男性、f：女性）：",
    "peso": "体重 [kg]：",
    "motivo": "予約の理由：",
    "error": "エラー",
    "error_edad": "年齢は正の数でなければなりません。",
    "error_peso": "体重は正の数でなければなりません。",
    "error_sexo": "性別は M または F でなければなりません。",
    "error_motivo": "予約の理由を入力してください。",
    "guarda_continuar": "保存して続行",
    "lista_medicos": "医師リスト",
    "busqueda_medicos": "医師検索",
    "ordenar_nombre": "名前で並べ替え",
    "ordenar_especialidad": "専門で並べ替え",
    "ordenar_precio": "価格で並べ替え",
    "foto": "写真",
    "especialidad": "専門",
    "precio": "価格（MXN）",
    "accion": "操作",
    "seleccionar": "選択",
    "cirugia_general": "一般外科",
    "neurocirugia": "脳神経外科",
    "diagnostico": "診断",
    "cirugia_cardiotoracica": "心臓胸部外科",
    "obstetricia": "産科 / 新生児科",
    "plastica": "形成外科 / 耳鼻咽喉科",
    "pediatrica": "小児外科",
    "oncologia": "腫瘍科",
    "cambiar_idioma": "言語を変更",
    "espaniol": "スペイン語",
    "ingles": "英語",
    "frances": "フランス語",
    "italiano": "イタリア語",
    "aleman": "ドイツ語",
    "chino": "中国語",
    "japones": "日本語",
    "portugues": "ポルトガル語",
    "titulo_ventana": "ログインシステム",
    "calendario": "カレンダー",
    "lunes": "月曜日",
    "martes": "火曜日",
    "miercoles": "水曜日",
    "jueves": "木曜日",
    "viernes": "金曜日",
    "sabado": "土曜日",
    "domingo": "日曜日",
    "horario": "スケジュール"
}
