textos = {
    "bienvenida": "Bem-vindo ao Sistema",
    "inicio_sesion_paciente": "Entrar como Paciente",
    "inicio_sesion_administrados": "Entrar como Administrador",
    "salir": "Sair",
    "iniciar_sesion_como": "Entrar como",
    "nombre": "Nome:",
    "correo_electronico": "E-mail:",
    "contrasena": "Senha:",
    "enviar": "Enviar",
    "regresar": "Voltar",
    "bienvenido": "Bem-vindo,",
    "citas_registradas": "Consultas Registradas",
    "horarios": "Horários",
    "registro_medico": "Registro Médico",
    "estadisticas": "Estatísticas",
    "historial_citas": "Histórico de usuários",
    "cerrar_sesion": "Encerrar Sessão",
    "edad": "Idade:",
    "sexo": "Sexo (m para masculino ou f para feminino):",
    "peso": "Peso [kg]:",
    "motivo": "Motivo da consulta:",
    "error": "Erro",
    "error_edad": "A idade deve ser um número positivo.",
    "error_peso": "O peso deve ser um número positivo.",
    "error_sexo": "O sexo deve ser M ou F.",
    "error_motivo": "O motivo da consulta não pode estar vazio.",
    "guarda_continuar": "Salvar e Continuar",
    "lista_medicos": "Lista de Médicos",
    "busqueda_medicos": "Busca de médicos",
    "ordenar_nombre": "Ordenar por Nome",
    "ordenar_especialidad": "Ordenar por Especialidade",
    "ordenar_precio": "Ordenar por Preço",
    "foto": "Foto",
    "especialidad": "Especialidade",
    "precio": "Preço (MXN)",
    "accion": "Ação",
    "seleccionar": "Selecionar",
    "cirugia_general": "Cirurgia Geral",
    "neurocirugia": "Neurocirurgia",
    "diagnostico": "Diagnóstico",
    "cirugia_cardiotoracica": "Cirurgia Cardiotorácica",
    "obstetricia": "Obstetrícia / Neonatal",
    "plastica": "Cirurgia Plástica / Otorrinolaringologia",
    "pediatrica": "Cirurgia Pediátrica",
    "oncologia": "Oncologia",
    "cambiar_idioma": "Mudar idioma",
    "espaniol": "Espanhol",
    "ingles": "Inglês",
    "frances": "Francês",
    "italiano": "Italiano",
    "aleman": "Alemão",
    "chino": "Chinês",
    "japones": "Japonês",
    "portugues": "Português",
    "titulo_ventana": "Sistema de Login",
    "calendario": "Calendário",
    "lunes": "Segunda-feira",
    "martes": "Terça-feira",
    "miercoles": "Quarta-feira",
    "jueves": "Quinta-feira",
    "viernes": "Sexta-feira",
    "sabado": "Sábado",
    "domingo": "Domingo",
    "horario": "Horário"
}
