textos = {
    "bienvenida": "Welcome to the System",
    "inicio_sesion_paciente": "Log in as Patient",
    "inicio_sesion_administrados": "Log in as Administrator",
    "salir": "Exit",
    "iniciar_sesion_como": "Log in as",
    "nombre": "Name:",
    "correo_electronico": "Email:",
    "contrasena": "Password:",
    "enviar": "Submit",
    "regresar": "Back",
    "bienvenido": "Welcome,",
    "citas_registradas": "Registered Appointments",
    "horarios": "Schedules",
    "registro_medico": "Medical Records",
    "estadisticas": "Statistics",
    "historial_citas": "User History",
    "cerrar_sesion": "Log out",
    "edad": "Age:",
    "sexo": "Sex (m for male or f for female):",
    "peso": "Weight [kg]:",
    "motivo": "Reason for the appointment:",
    "error": "Error",
    "error_edad": "Age must be a positive number.",
    "error_peso": "Weight must be a positive number.",
    "error_sexo": "Sex must be M or F.",
    "error_motivo": "The reason for the appointment cannot be empty.",
    "guarda_continuar": "Save and Continue",
    "lista_medicos": "List of Doctors",
    "busqueda_medicos": "Search for doctors",
    "ordenar_nombre": "Sort by Name",
    "ordenar_especialidad": "Sort by Specialty",
    "ordenar_precio": "Sort by Price",
    "foto": "Photo",
    "especialidad": "Specialty",
    "precio": "Price (MXN)",
    "accion": "Action",
    "seleccionar": "Select",
    "cirugia_general": "General Surgery",
    "neurocirugia": "Neurosurgery",
    "diagnostico": "Diagnosis",
    "cirugia_cardiotoracica": "Cardiothoracic Surgery",
    "obstetricia": "Obstetrics / Neonatal",
    "plastica": "Plastic Surgery / Otolaryngology",
    "pediatrica": "Pediatric Surgery",
    "oncologia": "Oncology",
     "cambiar_idioma": "Change language",
    "espaniol": "Spanish",
    "ingles": "English",
    "frances": "French",
    "italiano": "Italian",
    "aleman": "German",
    "chino": "Chinese",
    "japones": "Japanese",
    "portugues": "Portuguese",
    "titulo_ventana": "Login System",
    "calendario": "Calendar",
    "lunes": "Monday",
    "martes": "Tuesday",
    "miercoles": "Wednesday",
    "jueves": "Thursday",
    "viernes": "Friday",
    "sabado": "Saturday",
    "domingo": "Sunday",
    "horario": "Schedule"
}
