textos = {
    "bienvenida": "Willkommen im System",
    "inicio_sesion_paciente": "Als Patient anmelden",
    "inicio_sesion_administrados": "Als Administrator anmelden",
    "salir": "Beenden",
    "iniciar_sesion_como": "Anmelden als",
    "nombre": "Name:",
    "correo_electronico": "E-Mail:",
    "contrasena": "Passwort:",
    "enviar": "Senden",
    "regresar": "Zurück",
    "bienvenido": "Willkommen,",
    "citas_registradas": "Registrierte Termine",
    "horarios": "Zeitpläne",
    "registro_medico": "Medizinische Aufzeichnungen",
    "estadisticas": "Statistiken",
    "historial_citas": "Benutzerverlauf",
    "cerrar_sesion": "Abmelden",
    "edad": "Alter:",
    "sexo": "Geschlecht (m für männlich oder f für weiblich):",
    "peso": "Gewicht [kg]:",
    "motivo": "Grund für den Termin:",
    "error": "Fehler",
    "error_edad": "Das Alter muss eine positive Zahl sein.",
    "error_peso": "Das Gewicht muss eine positive Zahl sein.",
    "error_sexo": "Das Geschlecht muss M oder F sein.",
    "error_motivo": "Der Grund für den Termin darf nicht leer sein.",
    "guarda_continuar": "Speichern und Fortfahren",
    "lista_medicos": "Ärzteverzeichnis",
    "busqueda_medicos": "Arztsuche",
    "ordenar_nombre": "Nach Name sortieren",
    "ordenar_especialidad": "Nach Fachgebiet sortieren",
    "ordenar_precio": "Nach Preis sortieren",
    "foto": "Foto",
    "especialidad": "Fachgebiet",
    "precio": "Preis (MXN)",
    "accion": "Aktion",
    "seleccionar": "Auswählen",
    "cirugia_general": "Allgemeinchirurgie",
    "neurocirugia": "Neurochirurgie",
    "diagnostico": "Diagnose",
    "cirugia_cardiotoracica": "Herz-Thorax-Chirurgie",
    "obstetricia": "Geburtshilfe / Neonatal",
    "plastica": "Plastische Chirurgie / HNO",
    "pediatrica": "Kinderchirurgie",
    "oncologia": "Onkologie",
    "cambiar_idioma": "Sprache ändern",
    "espaniol": "Spanisch",
    "ingles": "Englisch",
    "frances": "Französisch",
    "italiano": "Italienisch",
    "aleman": "Deutsch",
    "chino": "Chinesisch",
    "japones": "Japanisch",
    "portugues": "Portugiesisch",
    "titulo_ventana": "Anmeldesystem",
    "calendario": "Kalender",
    "lunes": "Montag",
    "martes": "Dienstag",
    "miercoles": "Mittwoch",
    "jueves": "Donnerstag",
    "viernes": "Freitag",
    "sabado": "Samstag",
    "domingo": "Sonntag",
    "horario": "Zeitplan"
}
