textos = {
    "bienvenida": "Bienvenido al Sistema",
    "inicio_sesion_paciente": "Iniciar sesión como Paciente",
    "inicio_sesion_administrados": "Iniciar sesión como Administrador",
    "salir": "Salir",
    "iniciar_sesion_como": "Iniciar sesión como",
    "nombre": "Nombre:",
    "correo_electronico": "Correo Electrónico:",
    "contrasena": "Contraseña:",
    "enviar": "Enviar",
    "regresar": "Regresar",
    "bienvenido": "Bienvenido,",
    "citas_registradas": "Citas registradas",
    "horarios": "Horarios",
    "registro_medico": "Registro médico",
    "estadisticas": "Estadísticas",
    "historial_citas": "Historial de usuarios",
    "cerrar_sesion": "Cerrar sesión",
    "edad": "Edad:",
    "sexo": "Sexo (m para masculino o f para femenino):",
    "peso": "Peso[kg]:",
    "motivo": "Motivo de la cita:",
    "error": "Error",
    "error_edad": "La edad debe ser un número positivo.",
    "error_peso": "El peso debe ser un número positivo.",
    "error_sexo": "El sexo debe ser M o F.",
    "error_motivo": "El motivo de la cita no puede estar vacío.",
    "guarda_continuar": "Guarda y continuar",
    "lista_medicos": "Lista de médicos",
    "busqueda_medicos": "Busqueda de médicos",
    "ordenar_nombre": "Ordenar por nombre",
    "ordenar_especialidad": "Ordenar por especialidad",
    "ordenar_precio": "Ordenar por precio",
    "foto": "Foto",
    "especialidad": "Nombre",
    "precio": "Precio (MXN)",
    "accion": "Acción",
    "seleccionar": "Seleccionar",
    "cirugia_general": "Cirugía general",
    "neurocirugia": "Neurocirugía",
    "diagnostico": "Diagnóstico",
    "cirugia_cardiotoracica": "Cirugía cardiotorácica",
    "obstetricia": "Obstetricia / Neonatal",
    "plastica": "Cirugía plástica / Otorrino",
    "pediatrica": "Cirugía pediátrica",
    "oncologia": "Oncología",
    "cambiar_idioma": "Cambiar idioma",
    "espaniol": "Español",
    "ingles": "Ingles",
    "frances": "Frances",
    "italiano": "Italiano",
    "aleman": "Aleman",
    "chino": "Chino",
    "japones": "japones",
    "portugues": "portugues",
    "titulo_ventana": "Sistema de Inicio de Sesión",
    "calendario": "Calendario",
    "lunes": "Lunes",
    "martes": "Martes",
    "miercoles": "Miércoles",
    "jueves": "Jueves",
    "viernes": "Viernes",
    "sabado": "Sábado",
    "domingo": "Domingo",
    "horario": "Horario"
}
