textos = {
    "bienvenida": "Bienvenue dans le Système",
    "inicio_sesion_paciente": "Se connecter en tant que Patient",
    "inicio_sesion_administrados": "Se connecter en tant qu'Administrateur",
    "salir": "Quitter",
    "iniciar_sesion_como": "Se connecter en tant que",
    "nombre": "Nom:",
    "correo_electronico": "E-mail:",
    "contrasena": "Mot de passe:",
    "enviar": "Envoyer",
    "regresar": "Retour",
    "bienvenido": "Bienvenue,",
    "citas_registradas": "Rendez-vous Enregistrés",
    "horarios": "Horaires",
    "registro_medico": "Dossier Médical",
    "estadisticas": "Statistiques",
    "historial_citas": "Historique des utilisateurs",
    "cerrar_sesion": "Se Déconnecter",
    "edad": "Âge:",
    "sexo": "Sexe (m pour masculin ou f pour féminin):",
    "peso": "Poids [kg]:",
    "motivo": "Motif de la consultation:",
    "error": "Erreur",
    "error_edad": "L'âge doit être un nombre positif.",
    "error_peso": "Le poids doit être un nombre positif.",
    "error_sexo": "Le sexe doit être M ou F.",
    "error_motivo": "Le motif de la consultation ne peut pas être vide.",
    "guarda_continuar": "Enregistrer et Continuer",
    "lista_medicos": "Liste des Médecins",
    "busqueda_medicos": "Recherche de médecins",
    "ordenar_nombre": "Trier par Nom",
    "ordenar_especialidad": "Trier par Spécialité",
    "ordenar_precio": "Trier par Prix",
    "foto": "Photo",
    "especialidad": "Spécialité",
    "precio": "Prix (MXN)",
    "accion": "Action",
    "seleccionar": "Sélectionner",
    "cirugia_general": "Chirurgie Générale",
    "neurocirugia": "Neurochirurgie",
    "diagnostico": "Diagnostic",
    "cirugia_cardiotoracica": "Chirurgie Cardio-thoracique",
    "obstetricia": "Obstétrique / Néonatal",
    "plastica": "Chirurgie Plastique / ORL",
    "pediatrica": "Chirurgie Pédiatrique",
    "oncologia": "Oncologie",
    "cambiar_idioma": "Changer de langue",
    "espaniol": "Espagnol",
    "ingles": "Anglais",
    "frances": "Français",
    "italiano": "Italien",
    "aleman": "Allemand",
    "chino": "Chinois",
    "japones": "Japonais",
    "portugues": "Portugais",
    "titulo_ventana": "Système de connexion",
    "calendario": "Calendrier",
    "lunes": "Lundi",
    "martes": "Mardi",
    "miercoles": "Mercredi",
    "jueves": "Jeudi",
    "viernes": "Vendredi",
    "sabado": "Samedi",
    "domingo": "Dimanche",
    "horario": "Horaire"
}
