textos = {
    "bienvenida": "欢迎使用系统",
    "inicio_sesion_paciente": "以患者身份登录",
    "inicio_sesion_administrados": "以管理员身份登录",
    "salir": "退出",
    "iniciar_sesion_como": "登录身份",
    "nombre": "姓名：",
    "correo_electronico": "电子邮件：",
    "contrasena": "密码：",
    "enviar": "提交",
    "regresar": "返回",
    "bienvenido": "欢迎，",
    "citas_registradas": "已登记的预约",
    "horarios": "时间表",
    "registro_medico": "医疗记录",
    "estadisticas": "统计数据",
    "historial_citas": "用户历史",
    "cerrar_sesion": "注销",
    "edad": "年龄：",
    "sexo": "性别（m 表示男性，f 表示女性）：",
    "peso": "体重 [kg]：",
    "motivo": "预约原因：",
    "error": "错误",
    "error_edad": "年龄必须是正数。",
    "error_peso": "体重必须是正数。",
    "error_sexo": "性别必须是 M 或 F。",
    "error_motivo": "预约原因不能为空。",
    "guarda_continuar": "保存并继续",
    "lista_medicos": "医生列表",
    "busqueda_medicos": "搜索医生",
    "ordenar_nombre": "按姓名排序",
    "ordenar_especialidad": "按专业排序",
    "ordenar_precio": "按价格排序",
    "foto": "照片",
    "especialidad": "专业",
    "precio": "价格（MXN）",
    "accion": "操作",
    "seleccionar": "选择",
    "cirugia_general": "普通外科",
    "neurocirugia": "神经外科",
    "diagnostico": "诊断",
    "cirugia_cardiotoracica": "心胸外科",
    "obstetricia": "产科 / 新生儿科",
    "plastica": "整形外科 / 耳鼻喉科",
    "pediatrica": "小儿外科",
    "oncologia": "肿瘤科",
    "cambiar_idioma": "更改语言",
    "espaniol": "西班牙语",
    "ingles": "英语",
    "frances": "法语",
    "italiano": "意大利语",
    "aleman": "德语",
    "chino": "中文",
    "japones": "日语",
    "portugues": "葡萄牙语",
    "titulo_ventana": "登录系统",
    "calendario": "日历",
    "lunes": "星期一",
    "martes": "星期二",
    "miercoles": "星期三",
    "jueves": "星期四",
    "viernes": "星期五",
    "sabado": "星期六",
    "domingo": "星期日",
    "horario": "时间表"
}
